---
kind: Pod
apiVersion: v1
metadata:
  name: mypod2
spec:
  containers:
  - name: c01
    image: nginx
    command: ["/bin/bash", "-c", "while true; do echo Ankit; sleep 1500; done"]
  - name: c02
    image: httpd
    command: ["/bin/bash", "-c", "while true; do echo Ankit; sleep 1500; done"]